name: GitHub Metrics
on:
  # 毎日0時（UTC）に自動実行
  schedule:
    - cron: "0 0 * * *"
  # 手動実行も可能にする
  workflow_dispatch:
  # mainブランチへのpushでも実行
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/base.svg
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: header, activity, community, repositories
      - name: Most used
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/languages.svg
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_colors: C:#d65971, Java:#52828f, C++:#e3b248
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/isocalendar.fullyear.svg
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
      - name: Followers
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/people.followers.svg
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: followers